### ISSUE TITLE
EQ mixin outputting incorrect CSS

### ISSUE THREAD

**Issue by lmartins** [Snugug/eq.js#48]
Hi Sam,

I believe the eq mixin is still not outputting the correct css, but it now compiles on libsass and I believe its just a minor issue.

With the following:

``` sass
.loop--list{

    @include eq("large") {
        border: 1px solid red;
    }

```

What get compiled is:

``` css
.loop--list .loop--list[data-eq-state$='"large"'] {
    border: 1px solid red
}
```

Essentially it is repeating the `.loop--list` selector but placing the duplicated as a children of the first, so the code won't make any effect on the front-end.

Cheers.
