### ISSUE TITLE
eq.js doesn't render css selector in front of nested sass rules

### ISSUE THREAD

**Issue by mrbyte2001** [Snugug/eq.js#50]
# Used libs:

gulp-sass 2.0.4
or
gulp-ruby-sass 1.0.5 with sass 3.4.16
# Description

If you use something like this:

``` css
.outerclass {
   .innerclass {
     @include eq(small, med) {
         border: 1px solid black;
      }
    }
}
```

The resulting css will be:

``` css
.outerclass .innerclass[data-eq-state$="small"], .outerclass .innerclass[data-eq-state$="med"] {
   border: 1px solid black;
}
```

But it should be:

``` css
[data-eq-state$="small"] .outerclass .innerclass, [data-eq-state$="med"] .outerclass .innerclass {
  border: 1px solid black;
}
```

**Comment by Snugug** [comment]
Duplicate of https://github.com/Snugug/eq.js/issues/48

This is a Libsass and the correct thing is for it to be resolved there.

**Comment by mrbyte2001** [comment]
It's strange because I got the same result with gulp-ruby-sass as I wrote.
I am no sass expert but I think that if you put the & in front of anything the parent will be put in front. E.g.

``` css
.outerclass {
   &.innerclass {
     ...
   }
}
```

Result:

``` css
.outerclass.innerclass {
  ...
}
```

Instead:

``` css
.outerclass {
   .innerclass & {
     ...
   }
}
```

Renders to:

``` css
.innerclass .outerclass {
  ...
}
```

And its absolute logical for me.

``` css
.outerclass {
    @at-root &.innerclass {
        border: 1px solid green;
    }
}
```

Renders to:

``` css
.outerclass.innerclass {
  border: 1px solid green;
}
```

I think it's not needed to use @at-root. But to be sure you can use it to push the selector to the root.

So I don't think that this is a libsass or sass error. Maybe it was before and the error got fixed in sass?
But to be sure I will try to test it in another project with nothing more than your mixin and pure sass. I will inform you about the result.

**Comment by mrbyte2001** [comment]
I checked it with a pure compass project with following gems:
compass 1.0.3 and sass 3.4.16

``` css
.outerclass {
   @include eq(small, med) {
        border: 1px solid green;

    }
}
```

Renders to:

``` css
.outerclass[data-eq-state$="small"], .outerclass[data-eq-state$="med"] {
  border: 1px solid green;
}
```

**Comment by Snugug** [comment]
@mrbyte2001 https://github.com/Snugug/eq.js/issues/50#issuecomment-129168006 is the correct expected output.

http://sassmeister.com/gist/2fa73e6033ab96d37318

https://github.com/Snugug/eq.js/blob/1.x.x/sass/_eq.scss#L41-L45

**Comment by mrbyte2001** [comment]
Ok. But then I am confused about the usability of your lib. And to be honest it worked perfectly before I updated to the latest versions of the tools. To explain my confusion here is my problem I try to solve with eq.js (only a small piece of my code):

``` html
 <section class="c-content__body"
                 data-eq-pts="small: 0, med: 450, large: 810, xlarge: 990, xxlarge: 1180, xxxlarge: 1372">
           <ul class="card">
              <li class="address">... </li>
              <li class="details">... </li>
           </ul>
 </section>
```

I want to change the design of the inner list related to the space I have in the "c-content__body".
I use the following CSS:

``` css
.c-content__body {
   .card {
     @include span(6 of 8);
     border: 1px solid black;

     @include eq(small, med) {
       @include span (2 of 8);
       ...
     }
   }


}
```

Before I updated all of my libs I got the desired output:

``` css
[data-eq-state$="small"] .c-content__body .card, [data-eq-state$="med"] .c-content__body .card {
   ....
}
```

But now its:

``` css
.c-content__body .card[data-eq-state$="small"], .c-content__body .card[data-eq-state$="med"] {
  ...
}
```

Maybe I misunderstood css but the data-eq-state attribute is not on my tag with the "card"-class but on the tag with the "c-content__body"-class. And so nothing happens anymore. Before it said: "In the context of any item with the attribute 'data-eq-state' use following style". TBH I think better would be if the lib would render the class with the data-eq-state attribute in front of the selector if you have nested container, e.g.

``` css
 .c-content__body[data-eq-state$="small"] .card
```

Or is it needed to put the data-eq-pts attribute on everything I want to style in relation to the size? If so it would be a big repetition of the sizes and a big source of errors. And you should give an example for it in your README.
