### ISSUE TITLE
Mixin "EQSTATECHECK" does not accept a content block.

### ISSUE THREAD

**Issue by lmartins** [Snugug/eq.js#59]
Hi Sam,

Just to let you know that using latest beta releases from gulp-sass and node-sass the `eq` mixin throws the following error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: jspm_packages/github/Snugug/eq.js@1.7.1/sass/_eq.scss
  31:12  Mixin "EQSTATECHECK" does not accept a content block.

Backtrace:
    jspm_packages/github/Snugug/eq.js@1.7.1/sass/_eq.scss:31, in mixin `eq`
    src/sass/_shame.scss:469
    at options.error (/Users/luismartins/Sites/rulergy.dev/wp-content/themes/rulergy-marketing/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:277:32)
```

This with something like the following on my Sass file:

``` scss
.banner-home{
    @include eq-pts((
        small: 400,
        medium: 500,
        large: 700
    ));

    @include eq('small', 'medium', 'large') {
      font-size: 1em;
    }
}
```
